name: Initialise Pull Request

on:
  workflow_dispatch:
    inputs:
      DESCRIPTION:
        description: "Describe the changes"
        required: true
        default: "Deploy new ecommerce changes"
      TAG_KEY:
        description: "Tag Key"
        required: true
        default: "app"
      TAG_VALUE:
        description: "Tag Value"
        required: true
        default: "demo"

env:
  SOURCE_CLUSTER: ${{secrets.SOURCE_CLUSTER}}
  SOURCE_KEY_ID: ${{secrets.SOURCE_KEY_ID}}
  SOURCE_SECRET: ${{secrets.SOURCE_SECRET}}
  DESCRIPTION: ${{ inputs.DESCRIPTION }}
  TAG_KEY: ${{ inputs.TAG_KEY }}
  TAG_VALUE: ${{ inputs.TAG_VALUE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract resources by tag
      run: ./extract-resources-by-tag.sh

    - name: Create branch and pull request
      run: ./create-pr.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
