name: Initialise Pull Request

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag Name"
        required: true
        default: "app"
      TAG_VALUE:
        description: "Tag Value"
        required: true
        default: "demo"

env:
  SOURCE_CLUSTER: ${{secrets.SOURCE_CLUSTER}}
  SOURCE_KEY_ID: ${{secrets.SOURCE_KEY_ID}}
  SOURCE_SECRET: ${{secrets.SOURCE_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract resources by tag
      run: ./extract-resources-by-tag.sh ${{ inputs.TAG_NAME }} ${{ inputs.TAG_VALUE }}
